theme: jekyll-theme-minimal <img align="left" src="https://github.com/March-08/Machine-Learning-Journey/blob/main/Deep%20Learning/FlowerDetector/flower_detector.jpeg" height="290">
title: ğŸ’»âœ’ï¸ğŸ“„ğŸŒŸ
description: Marcello Politi's CV
